# Generated by Django 4.2.4 on 2023-09-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salery',
            new_name='salary',
        ),
    ]
